# Generated by Django 3.1.4 on 2020-12-18 09:54

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, validators=[blog.validators.validate_username], verbose_name='username')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('password', models.CharField(max_length=150, validators=[blog.validators.validate_password], verbose_name='password')),
                ('password2', models.CharField(max_length=150, verbose_name='password2')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
            ],
        ),
    ]
