# Generated by Django 3.1.4 on 2020-12-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'email', 'verbose_name_plural': 'emails'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
    ]
